### ISSUE TITLE
report content forms 

### ISSUE THREAD

**Issue by jackhftang** [benlau/ihatecontentfarms#26]
thegreatdaily.com
forum.key8.com    
www.money83.com // whole HK,
getez.info         // eznewlife
read01.com

**Comment by benlau** [comment]
Hi Jack,

Please report by using this google form:

https://docs.google.com/forms/d/e/1FAIpQLSc2bo8QTpX-qaIDcJ69UnGPLUO1Mr_9THVZZceSug-hcO3GGg/viewform
