### ISSUE TITLE
Fork for telegram bot

### ISSUE THREAD

**Issue by siutsin** [benlau/ihatecontentfarms#31]
Thanks for the brilliant plugin helped me over the past years. I have forked and used the site.js and created a bot for the Telegram messenger.

I would like to get your permission before distributing it, although it is still in very early development stage.

Due to Telegram API's restriction, the bot is not allowed to edit or delete any message other than its own. I will keep monitoring for any future changes.

Source code (GPLv3): [siutsin/ihatecontentfarms-telegram-bot](https://github.com/siutsin/ihatecontentfarms-telegram-bot)
Bot: [https://t.me/content_farm_bot](https://t.me/content_farm_bot)

<img width="601" alt="screen shot 2017-01-31 at 11 08 38 pm" src="https://cloud.githubusercontent.com/assets/904442/22470593/c5687aae-e80a-11e6-9057-b4808b07a741.png">
<img width="602" alt="screen shot 2017-01-31 at 11 03 38 pm" src="https://cloud.githubusercontent.com/assets/904442/22470603/cfb04a78-e80a-11e6-9ed2-b96a061df3c7.png">

**Comment by benlau** [comment]
hi @siutsin ,

Cool. No problem. Please feel free to use it.
