### ISSUE TITLE
Content farm report: zonghevip.com

### ISSUE THREAD

**Issue by ltsc1980** [benlau/ihatecontentfarms#44]
http://zonghevip.com/ is another content farm from happytify.cc

**Comment by benlau** [comment]
如想要求增加黑名單內的網站，請到以下網址：
https://docs.google.com/forms/d/15PiDGSjDMKorGFkoFKr76kW7NI02eD4IWL-O_OlM1GA/viewform

**Comment by ltsc1980** [comment]
我有要求了 但還是沒加進去 所以在這邊回報
